[onert-micro] Add kernels for GRU models
Samsung/ONE pull request #10565
Opened 2023-03-28 16:16 UTC by BalyshevArtem

This pr adds kernels for GRU models.

for issue https://github.com/Samsung/ONE/issues/10465

ONE-DCO-1.0-Signed-off-by: Artem Balyshev <a.balyshev@samsung.com>

2023-03-29 10:58 UTC, chunseoklee requested changes

2023-03-29 10:58 UTC, chunseoklee commented on onert-micro/CMakeLists.txt
> +    message(STATUS "ONERT-MICRO will use dynamic shapes")
```suggestion
    message(STATUS "ONERT-MICRO will not use dynamic shapes")
```

2023-03-29 11:57 UTC, chunseoklee commented on onert-micro/luci-interpreter/pal/mcu/pal.cmake
Any specific reason back to 2.6.0 ?

2023-03-29 12:46 UTC, SlavikMIPT approved these changes
LGTM

2023-03-30 07:43 UTC, BalyshevArtem commented on onert-micro/CMakeLists.txt
> +    message(STATUS "ONERT-MICRO will use dynamic shapes")
Done

2023-03-30 07:44 UTC, BalyshevArtem commented on onert-micro/luci-interpreter/pal/mcu/pal.cmake
For supporting TizenRT os purpose

2023-03-30 08:06 UTC, chunseoklee commented on onert-micro/luci-interpreter/pal/mcu/pal.cmake
@BalyshevArtem said that kernel of 2.8.0 has issue on std lib in tizenrt

2023-03-30 08:06 UTC, chunseoklee approved these changes

2023-03-30 09:51 UTC, SlavikMIPT approved these changes

2023-03-30 10:50 UTC, merged