[tflchef] Introduce a extype of Operation for custom operators
Samsung/ONE pull request #11753
Opened 2023-10-23 07:35 UTC by Seunghui98

This introduces a extype of Operation for custom operators.

ONE-DCO-1.0-Signed-off-by: SeungHui Lee <shsh1004.lee@samsung.com>

---
Related Issue: https://github.com/Samsung/ONE/issues/11741
Draft PR: https://github.com/Samsung/ONE/pull/11750

2023-10-23 12:54 UTC, mhs4670go approved these changes
LGTM

2023-10-23 21:35 UTC, seanshpark requested changes
this type is to be deleted. plz use `99`.
if you don't understand why I request with this, plz study about this item.

2023-10-24 01:45 UTC, Seunghui98 commented
@nnfw-bot test nncc-debug

2023-10-24 02:54 UTC, Seunghui98 commented
@seanshpark @mhs4670go 
As you commended, I modified the code in `tflchef` and `circlechef` modules.
Could you review it again??

2023-10-24 05:48 UTC, mhs4670go approved these changes

2023-10-24 05:49 UTC, seanshpark approved these changes
LGTM

2023-10-24 05:49 UTC, merged