[DRAFT][circle-quantizer] Support int4 quantization
Samsung/ONE pull request #12240
Opened 2023-12-07 10:48 UTC by SlavikMIPT

This commit supports int4 quantization.

ONE-DCO-1.0-Signed-off-by: Vyacheslav Bazhenov <slavikmipt@gmail.com>

2023-12-07 21:17 UTC, seanshpark requested changes
plz split loco and luci in different PRs

2023-12-07 21:18 UTC, seanshpark commented
Sorry for the comment. this was a DRAFT. Mind if I change this to DRAFT PR?

2024-02-20 10:36 UTC, BalyshevArtem commented on compiler/luci/export/src/CircleTensorExporter.cpp
> +  //Serialize int4 data
We also need method for deserialization for future testing this, right?

2024-03-06 01:45 UTC, seanshpark commented
@SlavikMIPT , I assume `int4` is for onert_micro.
We have some requirement to support `int4` for LLMs.
What is your target feature and end date of this?
As this draft existed several months, I assume you are on with other things, and if so can someone else in this side work on this topic?

2025-01-15 03:14 UTC, seanshpark commented
close as inactive for some time, feel free to reopen if needed

2025-01-15 03:14 UTC, closed without merging