[onert-micro] Add Softmax kernel
Samsung/ONE pull request #12742
Opened 2024-03-12 10:57 UTC by BalyshevArtem

This pr adds Softmax refactored kernel into onert-micro.

from draft https://github.com/Samsung/ONE/pull/12426
for issue: https://github.com/Samsung/ONE/issues/12427

ONE-DCO-1.0-Signed-off-by: Artem Balyshev <a.balyshev@samsung.com>

2024-03-12 12:49 UTC, SlavikMIPT requested changes

2024-03-13 09:25 UTC, BalyshevArtem commented on onert-micro/onert-micro/include/pal/common/PALSoftmaxCommon.h
> +      output_data[i * depth + c] = output_data[i * depth + c] / sum;
Done, add checking

2024-03-21 16:06 UTC, Torrero approved these changes
LGTM

2024-03-27 08:37 UTC, SlavikMIPT approved these changes
LGTM

2024-04-01 08:20 UTC, merged