[onert-micro] Add Split kernel
Samsung/ONE pull request #13250
Opened 2024-06-19 16:28 UTC by BalyshevArtem

This pr adds Split kernel.

ONE-DCO-1.0-Signed-off-by: Artem Balyshev <a.balyshev@samsung.com>

2024-06-20 12:30 UTC, SlavikMIPT requested changes

2024-06-20 12:30 UTC, SlavikMIPT commented on onert-micro/onert-micro/include/test_models/split/TestDataSplitBase.h
> + * Copyright (c) 2023 Samsung Electronics Co., Ltd. All Rights Reserved
```suggestion
 * Copyright (c) 2024 Samsung Electronics Co., Ltd. All Rights Reserved
```

2024-06-20 14:27 UTC, BalyshevArtem commented on onert-micro/onert-micro/include/test_models/split/TestDataSplitBase.h
> + * Copyright (c) 2023 Samsung Electronics Co., Ltd. All Rights Reserved
Done

2024-06-21 08:57 UTC, SlavikMIPT approved these changes
LGTM

2024-06-21 09:39 UTC, merged