[one-cmds] Fix invalid input arguments
Samsung/ONE pull request #4202
Opened 2020-09-10 23:22 UTC by seanshpark

This will fix error handling of invalid input arguments for import-tf, import-tflite and pack

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@samsung.com>

2020-09-10 23:22 UTC, seanshpark commented
For #4199

2020-09-10 23:48 UTC, lemmaa requested changes

2020-09-10 23:48 UTC, lemmaa commented on compiler/one-cmds/one-import-tf
> +  output_arrays_not_set
Perhaps?
```suggestion
  input_arrays_not_set
```

2020-09-11 00:36 UTC, llFreetimell approved these changes
LGTM

2020-09-11 01:04 UTC, lemmaa approved these changes
LGTM

2020-09-11 01:16 UTC, seanshpark commented
@nnfw-bot test nncc-debug

2020-09-11 01:16 UTC, seanshpark commented
@nnfw-bot test nncc-release

2020-09-11 01:24 UTC, seanshpark commented
@nnfw-bot test nncc-debug
@nnfw-bot test nncc-release

2020-09-11 01:24 UTC, seanshpark commented
@nnfw-bot test nncc-debug

2020-09-11 01:25 UTC, seanshpark commented
@nnfw-bot test nncc-release

2020-09-11 01:25 UTC, seanshpark commented
@nnfw-bot test nncc-debug

2020-09-11 02:41 UTC, merged