[onert] Support neon optimization for softmax
Samsung/ONE pull request #4430
Opened 2020-09-25 07:09 UTC by YiHyunJin

In softmax, it use neon optimizaion for exp operation.
So I added this, And tested any models. The result is an 1.5% increase in speed.
(1.346 -> 1.327)

Signed-off-by: YiHyunjin <hj0412.yi@samsung.com>

2020-09-27 23:06 UTC, glistening commented
@YiHyunJin As I guessed, this neon kernel (used in our model app) gives a slightly different value and lead errors like:

> pr-cross-runtime-test-pipeline-release/tests/nnapi/include/TestHarness.h:303: Failure 
> The difference between expected and actual is 1.0877847671508789e-05, which exceeds fpRange, 
> where expected evaluates to 0.086128540337085724, 
> actual evaluates to 0.086139418184757233, 

This kernel should be enclosed with build flag, that is not eabled by default, which is enabled only in the case that this difference is acceptable like our model.

2020-10-05 23:11 UTC, glistening commented on compute/cker/include/cker/operation/Exp.h
> +#ifdef USE_NEON
```suggestion
#if defined(USE_FAST_SOFTMAX) && defined(USE_NEON)
```

2020-10-05 23:11 UTC, glistening commented on compute/cker/include/cker/operation/Exp.h
> +#include "cker/neon/neon_check.h"
```suggestion
#if defined(USE_FAST_SOFTMAX)
#include "cker/neon/neon_check.h"
#endif
```

2020-10-05 23:11 UTC, glistening commented on compute/cker/include/cker/operation/SoftMax.h
> +#include "cker/operation/Exp.h"
```suggestion
#if defined(USE_FAST_SOFTMAX)
#include "cker/neon/neon_check.h"
#include "cker/operation/Exp.h"
#endif
```

2020-10-05 23:11 UTC, glistening commented on compute/cker/include/cker/operation/SoftMax.h
> +#ifdef USE_NEON
```suggestion
#if defined(USE_FAST_SOFTMAX) && defined(USE_NEON)
```

2020-10-05 23:14 UTC, glistening commented
@YiHyunJin Could you finish this PR?

1. Enclose this PR's change with `USE_FAST_SOFTMAX` or something else you'd like as I suggested
2. Introduce config variable `USE_FAST_SOFTMAX` in `CfgOptionFlags.cmake` with default `OFF`. 
3. Define `USE_FAST_SOFTMAX` only when `USE_FAST_SOFTMAX` is `ON`.

2020-10-06 23:11 UTC, glistening requested changes

2020-10-06 23:11 UTC, glistening commented on infra/nnfw/cmake/CfgOptionFlags.cmake
> +option(BUILD_FAST_SOFTMAX "Build mlapse benchmark toolkit" OFF)
```suggestion
option(USE_FAST_SOFTMAX "Use fast but approximated softmax" OFF)
```

2020-10-06 23:11 UTC, glistening commented on infra/nnfw/cmake/CfgOptionFlags.cmake
> +
@YiHyunJin Please move those lines out of `CfgOptionFlags.cmake`. There are no logic in this file. `compute/cker/CMakeLists.txt` looks good.

2020-10-06 23:15 UTC, glistening commented
@YiHyunJin If we provides approximate but fast softmax kernel as build option defaulted off, it cannot be used unless building again. It may be better to provide runtime option instead of build option so that it can be selected by other runtime configuration. However, as I know, we need to provide a way for user to change runtime configuration.

cc @wateret

2020-10-26 04:13 UTC, closed without merging

2020-10-26 04:28 UTC, YiHyunJin commented
The effect was insignificant, so it was closed.