[onert] Optimize in StridedSlice
Samsung/ONE pull request #4508
Opened 2020-10-06 09:38 UTC by YiHyunJin

when only last dimension used, we have easy accesse to index.
So I optimized it for that situation.
And tested any models. The result is an 3.5% increase in speed.
(1.233 -> 1.191)

Signed-off-by: YiHyunjin <hj0412.yi@samsung.com>

2020-10-07 03:46 UTC, glistening commented on compute/cker/include/cker/operation/StridedSlice.h
> +  }
@YiHyunJin Why don't you check in KernelGenerator?

2020-10-07 07:09 UTC, wateret commented
> @YiHyunJin Why don't you check in KernelGenerator?

How was this resolved? It looks like the param check is done in the kernel. Just adding some more description, for example,

- Split the optimized kernel and original kernel into two separate functions
- As we know the params at prepare(compile) time, move the param check code in KernelGenerator
- Then we are able to bind the most proper kernel for that single operation node, and no need to check it at execution time

BTW it looks good itself and this work can be done after merging this PR.

2020-10-07 07:12 UTC, wateret requested changes
Please add a test case (for code coverage and verification)

2020-10-07 07:12 UTC, wateret commented
@nnfw-bot test android-runtime-builder

2020-10-07 07:12 UTC, glistening commented
`android-runtime-builder` fails because downloading 'http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz' failed.

2020-10-07 08:24 UTC, glistening commented
I've write testcase for this PR using CircleGen. Please see #4525.

2020-10-07 09:52 UTC, wateret commented
@YiHyunJin Could you please respond https://github.com/Samsung/ONE/pull/4508#issuecomment-704742171 ?

2020-10-07 10:00 UTC, YiHyunJin commented
@wateret It looks good to do after `buildStridedSliceParams`.
So I checked in `StridedSlice`.

> BTW it looks good itself and this work can be done after merging this PR.
Yes~

2020-10-07 11:04 UTC, glistening approved these changes
LGTM

2020-10-07 11:28 UTC, wateret approved these changes
LGTM

2020-10-07 11:28 UTC, merged

2020-10-07 23:12 UTC, glistening commented
@YiHyunJin This morning, I've tested with merged PR. In my environment (a bit different model), this PR does not make differences for our target model.

1.010 → 1.005 (about 0.49% improvement)

2020-10-08 01:46 UTC, YiHyunJin commented
@glistening  I checked this problem and i fixed.
https://github.com/Samsung/ONE/pull/4543