[onert] Allows variable tensor
Samsung/ONE pull request #4655
Opened 2020-10-16 05:27 UTC by ragmani

For issue #3851

This commit allows variable tensor.
  - Introduces a field checking variable tensor into OperandInfo
  - Apply variable tensor

Signed-off-by: ragmani <ragmani0216@gmail.com>

2020-10-16 07:33 UTC, wateret requested changes
Could you please explain what is difference between non-const(`IsConstant()` is false) and variable tensors?

2020-10-16 08:07 UTC, ragmani commented
> Could you please explain what is difference between non-const(IsConstant() is false) and variable tensors?

@wateret 
Variable tensor means mutable tensor. And TFLite interpreter only supports variable tensor without buffers in the model.

2020-10-16 09:24 UTC, wateret approved these changes
LGTM, I heard the explanation offline.

- `is_variable` is an explicit flag which is present in tflite schema
- No operation generates it (like constants)
- It does not have data (unlike constants)
- Only one operation is allowed to use a variable tensor
- Seems like it is used as a temp space to store the current state (not 100% sure)

2020-10-19 01:29 UTC, hseok-oh approved these changes

2020-10-19 01:29 UTC, merged