[onert] Add more ops into OneOp_While test
Samsung/ONE pull request #4905
Opened 2020-11-03 10:24 UTC by hyunsik-yoon

This add `cast` before calling `while` and 
add another `cast` after calling `while`. 

This is to check if input and output of `while` is handled well.

for issue https://github.com/Samsung/ONE/issues/4901 to check if we also see other ops well before and after `while`.

Signed-off-by: Hyun Sik Yoon <hyunsik.yoon.1024@gmail.com>

2020-11-03 10:34 UTC, wateret requested changes
What about adding another test for this?

2020-11-03 10:44 UTC, hyunsik-yoon commented
You want to keep `oneOp` test for only one op? I see. :-)

2020-11-03 11:06 UTC, wateret commented
@hyunsik-yoon Breaking "one-op" category is OK. I would allow some tests that have more than one ops are in "one-op" test dir. But I would like to keep the model tests that have just one operation. I find them useful when debugging. 😃

2020-11-03 11:49 UTC, hyunsik-yoon commented
I moved the same test to `GenModelTests.cc`.
Since I have to add one more negative test, I added a negative test.
Thanks.

2020-11-04 06:40 UTC, wateret approved these changes
LGTM

2020-11-04 06:40 UTC, merged