[onert] Introduce xnnpack backend
Samsung/ONE pull request #5021
Opened 2020-11-12 02:34 UTC by YongseopKim

Introduce xnnpack backend

ONE-DCO-1.0-Signed-off-by: Yongseop Kim <yons.kim@samsung.com>

2020-11-12 02:34 UTC, YongseopKim commented
for #4968

2020-11-13 05:02 UTC, YongseopKim commented
xnnpack on onert: https://github.com/Samsung/ONE/pull/5034

2020-11-13 07:34 UTC, YongseopKim commented
Current status

```
odroid@odroid:/home/dragon/Works/github/ONE$ ONERT_LOG_ENABLE=0 BACKENDS="xnnpack" OP_BACKEND_Conv2D="xnnpack" ./Product/out/bin/nnapi_test ./tests/scripts/framework/cache/conv_2d/convolution2/convolution_test2.tflite
...
[NNAPI TEST #1] PASSED
...
[NNAPI TEST #2] PASSED
```

```
odroid@odroid:/home/dragon/Works/github/ONE$ BACKENDS="cpu;xnnpack" OP_BACKEND_Conv2D="xnnpack" ./Product/out/bin/nnapi_test ./tests/scripts/framework/cache/MODELS/inception_module/inception_test.tflite
...
[NNAPI TEST #1] PASSED
...
[NNAPI TEST #2] PASSED
```

2020-11-16 09:37 UTC, chunseoklee commented
@YongseopKim Current PR uses 1 thread ?

2020-11-16 09:41 UTC, YongseopKim commented
@chunseoklee maybe yes. I don't touch any thread setting. Therefore, the default thread num would be set.

2020-11-19 06:30 UTC, periannath commented on runtime/onert/backend/xnnpack/ops/DepthwiseConvolutionLayer.cc
> +      0 /* flags */, &_kernel_op);
@YongseopKim `XNN_FLAG_DEPTHWISE_CONVOLUTION` flag might be needed at here. https://github.com/google/XNNPACK/blob/9cef5eabcb5cc408db468abc0009dc424a852272/src/runtime.c#L354

2020-11-19 08:06 UTC, YongseopKim commented
```
ONERT_LOG_ENABLE=1 BACKENDS="cpu;xnnpack" OP_BACKEND_Conv2D="xnnpack" OP_BACKEND_DepthwiseConv2D="xnnpack" ./Product/out/bin/nnapi_test tests/scripts/framework/cache/depthwise_conv_2d/depthconv1/depth_conv_test1.tflite
```

2020-11-19 08:07 UTC, YongseopKim commented
@nnfw-bot help

2020-11-19 08:07 UTC, YongseopKim commented
@nnfw-bot test all

2020-11-19 08:16 UTC, YongseopKim commented
TODO
- Remove permutation
- Release unused const tensors

2020-11-19 08:16 UTC, YongseopKim commented
PTAL @periannath and @chunseoklee

2020-11-19 08:18 UTC, YongseopKim commented
@nnfw-bot test x64-builder

2020-11-19 08:23 UTC, chunseoklee submitted a review, later dismissed

2020-11-20 01:51 UTC, ragmani commented
@nnfw-bot test cross-runtime-test-debu

2020-11-20 01:51 UTC, ragmani commented
@nnfw-bot test cross-runtime-test-debug

2020-11-20 01:51 UTC, ragmani commented
@nnfw-bot test android-runtime-builder

2020-11-20 03:13 UTC, YongseopKim commented
Thanks @ragmani

2020-11-20 03:14 UTC, YongseopKim commented
PTAL @chunseoklee and @periannath

2020-11-20 04:27 UTC, periannath requested changes

2020-11-20 04:27 UTC, periannath commented on tests/nnfw_api/src/one_op_tests/Conv2D.cc
> +  _context->setBackends({"acl_cl", "acl_neon", "cpu", "ruy", "xnnpack"});
I just found that you have to add `xnnpack` to `GenModelTestContext::setBackends`. https://github.com/Samsung/ONE/blob/c46ddc04abdb58323fbd38389e6927f003bfaea1/tests/nnfw_api/src/GenModelTest.h#L215

Without that line, `xnnpack` will not be tested on `GenModelTest`.

2020-11-20 08:05 UTC, YongseopKim commented
PTAL @chunseoklee and @periannath

2020-11-23 02:03 UTC, periannath approved these changes
LGTM

2020-11-23 02:51 UTC, chunseoklee approved these changes

2020-11-23 02:51 UTC, merged