[onert] Introduce MEAN cpu kernel specialized for axis=1,2
Samsung/ONE pull request #5178
Opened 2020-11-26 05:29 UTC by glistening

It brings MEAN cpu kernel specialized for axis=1,2 from tflite.
That is, reduce over axis of width and height.

ONE-DCO-1.0-Signed-off-by: Sanggyu Lee <sg5.lee@samsung.com>

2020-11-26 05:30 UTC, glistening commented
It accelerates a target model with `mean` from 275 ms to 226 ms.

2020-11-26 05:42 UTC, hseok-oh approved these changes

2020-11-26 05:46 UTC, periannath submitted a review, later dismissed
LGTM

2020-11-26 06:26 UTC, wateret requested changes

2020-11-26 06:26 UTC, wateret commented on tests/nnfw_api/src/one_op_tests/Mean.cc
> +TEST_F(GenModelTest, OneOp_neg_Mean)
```suggestion
TEST_F(GenModelTest, neg_OneOp_Mean)
```

2020-11-26 07:23 UTC, glistening commented
@wateret, @periannath , @hseok-oh PTAL

2020-11-26 07:26 UTC, hseok-oh approved these changes

2020-11-26 07:30 UTC, periannath approved these changes
LGTM

2020-11-27 01:18 UTC, wateret approved these changes

2020-11-27 01:18 UTC, merged